# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/service.proto\x12\x05proto\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1d\n\x0cPingResponse\x12\r\n\x05reply\x18\x01 \x01(\t2>\n\x0b\x43oreService\x12/\n\x04Ping\x12\x12.proto.PingRequest\x1a\x13.proto.PingResponseB\x14Z\x12gocore/proto;protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022gocore/proto;proto'
  _globals['_PINGREQUEST']._serialized_start=30
  _globals['_PINGREQUEST']._serialized_end=60
  _globals['_PINGRESPONSE']._serialized_start=62
  _globals['_PINGRESPONSE']._serialized_end=91
  _globals['_CORESERVICE']._serialized_start=93
  _globals['_CORESERVICE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
